### ISSUE TITLE
Build a .1 version of a marine debris app

### ISSUE THREAD

**Issue by metanomy** [metanomy/marinedebrisapp#1]
1. Hybrid app based on Ionic framework for both Android and iOS.
2. Opening app should immediately activate the camera.
3. If GPS is not active, an overlay onto the camera preview should prompt user to activate GPS
4. Once a photo is taken, camera should re-activate (might require user accepting photo, determined by mobile platform)
5. Photo and GeoJSON should be pushed to a server (if disconnected, cached until connected). 
   - Lat/lon should come from photo exif, or from device GPS.
   - GeoJSON should include photo URL attribute

**Comment by tiepduong7c9** [comment]
Hello, Is this issue still active?

**Comment by metanomy** [comment]
@smartgoat We just had someone finish this using React instead of Ionic, and the code should be up in the repo soon. Once it is, we'll close the issue out.

On a related note, we do have some additional features to add to the React app:
- Ability to trigger the camera from the audio jack
- Eliminating the need for the user to select "OK" after each photo.

Those features are (I think) native to iOS, but for Android it's going to require us to write a custom model.

**Comment by targeter21** [comment]
Hi, is this issue fully done then?

**Comment by metanomy** [comment]
Yes, closing it out.
